### ISSUE TITLE
Menus API is slow >10sec

### ISSUE THREAD

**Issue by aruchames** [ColonialDevelopment/website#10]
The menus API is slow to the point that it is unusable. 

1. Refactor the API such that it only returns a day at a time. This will require frontend work as well to re-query on changing day. (currently building all of the menus ever in order to make a first return)
2. Refactor the ratings API such that average rating is stored on a dish and calculated after each call to post a rating. (currently filtering all the ratings ever for every dish in order to display average rating on a single request)

These two changes should make the menus page fast enough. If you want further optimization you might need to change the way user rating is displayed. For instance you could only query for the user's rating of a dish after the user has popped up the modal.

**Comment by aruchames** [comment]
@vzhou842 or @nackster12  can you post some proof of perf gain and close this bug?

**Comment by vzhou842** [comment]
<img width="1435" alt="screen shot 2018-02-12 at 5 46 42 pm" src="https://user-images.githubusercontent.com/10209814/36124053-b64f4cd8-101c-11e8-915a-18f217223cbf.png">

400 ms request
